### PR TITLE
doing things the "right" way.

### PR DESCRIPTION
**Pull request by Drewzar**
This will clone `arrakis-hubot` to your local file system (where you should be doing your editing), install all the deps needed to make hubot run.

Workflow will be:

```
> git clone git@github.com:desert-planet/vagrant-hubot.git
> vagrant status (this clones `arrakis-hubot`)
```

Make your changes in the newly cloned `arrakis-hubot` repo

```
> vagrant up
> vagrant ssh
$ cd arrakis/arrakis-hubot
$ bin/hubot
```

Test your feature

### CODE REVIEW

**Comment by Drewzar** [comment]
I like to explicitly set that cause I've seen vagrant do weird thing, also it help for people who jump between vagrant providers (IE me).

**Comment by drobati** [comment]
Ah. Thanks for the explanation. Makes sense.

**Comment by Drewzar** [comment]
In short, you shouldn't ever have to do anything _inside_ the vagrant vm other than run hubot.

**Comment by Drewzar** [comment]
Go ahead a check this branch out and test and let me know :smile:  

cc/ @desert-planet/fremen

**Comment by drobati** [comment]
I can't test it for another hour. I'll let you know by this afternoon.

**Comment by skalnik** [comment]
What the fuck is this? Why did I get pinged

**Comment by drobati** [comment]
Vagrant for hubot.

**Comment by drobati** [comment]
Instructions in README didn't add up. I think it's missing the `vagrant status` command?

**Comment by drobati** [comment]
Also the git pull didn't work because I'm behind a firewall. Is it possible to change that to https?

**Comment by drobati** [comment]
@Drewzar This didn't work for me. I had an issue with bin/hubot.

`-bash: bin/hubot: /bin/sh^M: bad interpreter: No such file or directory`

**Comment by drobati** [comment]
http://stackoverflow.com/questions/2920416/configure-bin-shm-bad-interpreter

This page indicates the DOS line-ending in the file? I wonder how that happened to bin/hubot?!

**Comment by drobati** [comment]
So the issue is maybe git on windows needs to be configured to use unix line endings.

**Comment by drobati** [comment]
I suspect that since `vagrant status` is executed with windows' `git` it adds in DOS line endings to the files. And if I recall I think there is even an option for maintaining the source repos line endings. Not sure how Github for Windows switched it to convert to windows.

**Comment by Drewzar** [comment]
Sorry, I have very little to no experience using git on windows. Let me know what you find.

**Comment by drobati** [comment]
:+1: Good job, @Drewzar

**Pull request merged**
