### PR TITLE
Fixing issue with npm test.

### LINKED ISSUE #8: 'npm test' is missing dependencies OOTB
We should 'npm install' in the vagrant init script. :)

### PR DESCRIPTION
**Pull request by drobati**
These commits fix the issue with `npm test` failing.

It is current a work in progress.

I will comment when I have manually tested that it worked!
#8

### CODE REVIEW

**Comment by drobati** [comment]
So this didn't work. @sshirokov `npm install` had issues.

`bin/hubot` seems to work better for some reason.

**Comment by sshirokov** [comment]
> So this didn't work. @sshirokov npm install had issues.
> 
> bin/hubot seems to work better for some reason.

That doesn't sound right, since [bin/hubot calls `npm install`](https://github.com/desert-planet/arrakis-hubot/blob/master/bin/hubot#L3)

**Comment by drobati** [comment]
`bin/hubot` is broken now.

**Comment by sshirokov** [comment]
Fixed by #10

**Pull request closed without merging**
